### ISSUE TITLE
Issue with JSON on Vercel

### ISSUE THREAD

**Issue by abdinal1** [langgenius/webapp-conversation#12] opened 2023-06-26 18:48 UTC
Hello,

When pushing the repo to vercel I can type a chat message, seldom it does deliever an answer and mostly an JSON error appears:

"SyntaxError: Unterminated string in JSON at position 129"

This error always pops up when I want to type something, why is that so? Please help me.

**Comment by abdinal1** [comment] 2023-07-02 13:39
Do you have any ideas @goocarlos @iamjoel @jingjingxinshang @crazywoola ?

**Comment by yalefox** [comment] 2023-07-25 14:38
We're getting the same errors - it happens when you modify config.ts

**Comment by abdinal1** [comment] 2023-07-26 13:35
@yalefox And what is the solution ?

**Comment by iamjoel** [comment] 2023-08-29 05:45
This issue is a duplicate of https://github.com/langgenius/webapp-conversation/issues/13

**Closed by iamjoel** 2023-08-29 05:45 UTC
